version: 2.1
orbs:
  node: circleci/node@3.0.1
jobs:
  deliver:
    steps:
      - checkout
      - run: yarn install
      - run: cd client
      - run: yarn install
      - run: yarn build
      - run: cd ..
      - run:
        name: Deploy over SSH
        command: |
          ssh $SSH_USER@$SSH_HOST
